language: python

python:
    - 3.6

services:
  - mongodb

sudo: enabled

before_install:
 - sudo apt-get update
 - sudo apt-get install -y git
 - sudo apt-get install -y python3 python3-dev python3-pip
 - sudo apt-get install -y curl
 - sudo apt-get install -y jq
 # Install OPA and bpm bundle
 - curl -o opa https://github.com/open-policy-agent/opa/releases/download/v0.9.2/opa_linux_amd64
 - chmod 755 ./opa
 - curl -O $(curl "https://api.github.com/repos/ioet/bpm-opa/releases/latest" | jq -r '.assets[0].browser_download_url')
 # Run OPA this way until this issue be solved https://github.com/open-policy-agent/opa/issues/1019
 - tar -xvzf bpm.tar.gz
 - opa run -s bpm

# install dependencies
install:
  - pip3 install -r requirements/azure-dev.txt
  - pip3 install codecov
  #Initialize the database
  - python3 cli.py init_db
  #Run OPA

script:
  #PEP 8
  - flake8 bpm_projects_api --count
  #Tests and Coverage
  - coverage erase
  - coverage run -m pytest -v
  #80% of the code should be covered
  - coverage html --fail-under=80

after_success:
  - codecov
